from quiz_settings import MenuItems as mi


# Панели кнопок
COUNT_END_KEYBOARD = [mi.SCORE, mi.FINISH]
GIVEUP_KEYBOARD = [[mi.GIVE_UP], [mi.FINISH]]
NEW_QUESTION_KEYBOARD = [[mi.NEW_QUESTION], COUNT_END_KEYBOARD]
NEW_QUIZ_KEYBOARD = [[mi.NEW_QUIZ, mi.QUIT]]
START_KEYBOARD = [[mi.NEW_QUESTION], [mi.FINISH]]
